# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias ipython="ipython --colors Linux"
alias Projects="cd ~/Programming/Projects"
alias Libraries="cd ~/Programming/Libraries"
alias DailyProjects="cd ~/Programming/Github/DailyProjects"
alias perf_common="perf stat -e branches,branch-misses,cache-references,cache-misses,cpu-migrations,context-switches,page-faults,stalled-cycles-frontend,stalled-cycles-backend,instructions,cycles"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git github svn vi-mode python gnu-utils mercurial)

source $ZSH/oh-my-zsh.sh

set -o vi
export EDITOR=vim
export PYTHONSTARTUP=$HOME/.pythonrc.py
