((lambda (Y for-each fib)
   ((Y for-each) (lambda (i) ((Y fib) 0 1 i)) 0 40)
   )
 (lambda (f)
   ((lambda (Y) (Y Y))
    (lambda (Y-self)
      (f (lambda (a b c d e) ((Y-self Y-self) a b c d e))))))
 (lambda (self)
   (lambda (f i n)
     (print (f i))
     (if (= i n)
       i
       (self f (+ i 1) n))
     ))
 (lambda (self)
   (lambda (a b n)
     (if (= n 0)
       a
       (self b (+ a b) (- n 1)))
     )))
