#! /usr/bin/env python
# coding=utf-8

import time

def getMdays():
    now = time.localtime()
    if now.tm_mon in (1,3,5,7,8,10,12): return 31
    elif now.tm_mon in (4,6,9,11): return 30
    else:
        if now.tm_year % 4 == 0 and (
        now.tm_year % 100 != 0 or now.tm_year % 400 == 0): 
            return 29
        else: return 28

def printCal():
    now = time.localtime()
    print ' ' * 5 + time.strftime('%Y年%m月', now)
    print '日 一 二 三 四 五 六',
    mdays = getMdays()
    remain = (now.tm_wday + (8 - now.tm_mday % 7) + 1) % 7
    day = 1
    for i in range(1, 100):
        if i % 7 == 1: print 
        if i <= remain: 
            print ' ' * 2, 
            continue
        if day > mdays: break
        print '%2d' % day,
        day += 1

printCal()
