(define n 0)
(define (putc c)
  (if (<= n 100)
    (begin (set! n (+ n 1)) (display c))
    (exit))
  )

(let ([yin ((lambda (cc) (putc 1) cc) (call/cc (lambda (c) c)))])
  (let ([yang ((lambda (cc) (putc 0) cc) (call/cc (lambda (c) c)))])
    (yin yang)))
